# Generated by Django 5.0.6 on 2024-07-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('UnMed', models.CharField(max_length=20)),
                ('ValorVenda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ValorCompra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
