# Generated by Django 4.2.8 on 2024-07-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='CodBarra',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
