# Generated by Django 4.2.8 on 2024-05-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
    ]
