# Generated by Django 4.2.8 on 2024-07-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
    ]
