# Generated by Django 4.2.8 on 2024-07-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usuario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('vendedor', 'Vendedor'), ('caixa', 'Caixa'), ('funcionario', 'Funcionario')], max_length=20, null=True),
        ),
    ]
